// Generated by scripts/crop-chapters.py. Do not hand-edit.
//
// The diagram facing each chapter introduction in the printed journal,
// with its quotation set into the artwork.

export type ChapterVisual = { src: string; width: number; height: number }

const chapters: Record<number, ChapterVisual> = {
  1: { src: '/journal/chapters/w01.webp', width: 768, height: 607 },
  2: { src: '/journal/chapters/w02.webp', width: 610, height: 661 },
  3: { src: '/journal/chapters/w03.webp', width: 697, height: 797 },
  4: { src: '/journal/chapters/w04.webp', width: 742, height: 947 },
  5: { src: '/journal/chapters/w05.webp', width: 423, height: 1008 },
  6: { src: '/journal/chapters/w06.webp', width: 494, height: 794 },
  7: { src: '/journal/chapters/w07.webp', width: 853, height: 641 },
  8: { src: '/journal/chapters/w08.webp', width: 358, height: 489 },
  9: { src: '/journal/chapters/w09.webp', width: 770, height: 755 },
  10: { src: '/journal/chapters/w10.webp', width: 394, height: 727 },
  11: { src: '/journal/chapters/w11.webp', width: 746, height: 539 },
  12: { src: '/journal/chapters/w12.webp', width: 601, height: 870 },
  13: { src: '/journal/chapters/w13.webp', width: 775, height: 291 },
  14: { src: '/journal/chapters/w14.webp', width: 681, height: 402 },
  15: { src: '/journal/chapters/w15.webp', width: 775, height: 477 },
  16: { src: '/journal/chapters/w16.webp', width: 865, height: 841 },
}

export function chapterVisual(week: number): ChapterVisual | null {
  return chapters[week] ?? null
}
