// Generated by scripts/crop-elite-visuals.py. Do not hand-edit.
//
// The artwork from each Elite entry page, cropped away from the ruled
// writing lines and the prompt boxes. Rendered on a flat ground with
// multiply blending, so the white of the page drops out.

import type { Visual } from './journal-visuals'

const eliteVisuals: Record<number, Visual> = {
  1: { src: '/journal/elite-visuals/e001.webp', width: 883, height: 879 },
  10: { src: '/journal/elite-visuals/e010.webp', width: 686, height: 614 },
  16: { src: '/journal/elite-visuals/e016.webp', width: 891, height: 481 },
  22: { src: '/journal/elite-visuals/e022.webp', width: 651, height: 218 },
  32: { src: '/journal/elite-visuals/e032.webp', width: 729, height: 767 },
  38: { src: '/journal/elite-visuals/e038.webp', width: 709, height: 381 },
  44: { src: '/journal/elite-visuals/e044.webp', width: 626, height: 344 },
  50: { src: '/journal/elite-visuals/e050.webp', width: 548, height: 548 },
  60: { src: '/journal/elite-visuals/e060.webp', width: 798, height: 473 },
  66: { src: '/journal/elite-visuals/e066.webp', width: 793, height: 549 },
  69: { src: '/journal/elite-visuals/e069.webp', width: 1063, height: 546 },
  78: { src: '/journal/elite-visuals/e078.webp', width: 674, height: 826 },
  85: { src: '/journal/elite-visuals/e085.webp', width: 712, height: 705 },
  88: { src: '/journal/elite-visuals/e088.webp', width: 763, height: 519 },
  94: { src: '/journal/elite-visuals/e094.webp', width: 428, height: 397 },
  97: { src: '/journal/elite-visuals/e097.webp', width: 868, height: 798 },
  100: { src: '/journal/elite-visuals/e100.webp', width: 574, height: 592 },
  103: { src: '/journal/elite-visuals/e103.webp', width: 826, height: 798 },
  116: { src: '/journal/elite-visuals/e116.webp', width: 757, height: 396 },
  122: { src: '/journal/elite-visuals/e122.webp', width: 310, height: 608 },
  128: { src: '/journal/elite-visuals/e128.webp', width: 693, height: 622 },
  134: { src: '/journal/elite-visuals/e134.webp', width: 583, height: 1177 },
  144: { src: '/journal/elite-visuals/e144.webp', width: 697, height: 519 },
  150: { src: '/journal/elite-visuals/e150.webp', width: 533, height: 485 },
  156: { src: '/journal/elite-visuals/e156.webp', width: 688, height: 573 },
  162: { src: '/journal/elite-visuals/e162.webp', width: 806, height: 275 },
  172: { src: '/journal/elite-visuals/e172.webp', width: 593, height: 546 },
  178: { src: '/journal/elite-visuals/e178.webp', width: 461, height: 542 },
  184: { src: '/journal/elite-visuals/e184.webp', width: 732, height: 453 },
  190: { src: '/journal/elite-visuals/e190.webp', width: 589, height: 690 },
  200: { src: '/journal/elite-visuals/e200.webp', width: 598, height: 360 },
  206: { src: '/journal/elite-visuals/e206.webp', width: 644, height: 403 },
  212: { src: '/journal/elite-visuals/e212.webp', width: 590, height: 612 },
  218: { src: '/journal/elite-visuals/e218.webp', width: 594, height: 677 },
  228: { src: '/journal/elite-visuals/e228.webp', width: 606, height: 605 },
  234: { src: '/journal/elite-visuals/e234.webp', width: 630, height: 658 },
  240: { src: '/journal/elite-visuals/e240.webp', width: 544, height: 582 },
  246: { src: '/journal/elite-visuals/e246.webp', width: 610, height: 1028 },
  253: { src: '/journal/elite-visuals/e253.webp', width: 835, height: 651 },
  256: { src: '/journal/elite-visuals/e256.webp', width: 697, height: 297 },
  259: { src: '/journal/elite-visuals/e259.webp', width: 835, height: 651 },
  262: { src: '/journal/elite-visuals/e262.webp', width: 540, height: 747 },
  265: { src: '/journal/elite-visuals/e265.webp', width: 835, height: 651 },
  268: { src: '/journal/elite-visuals/e268.webp', width: 618, height: 651 },
  274: { src: '/journal/elite-visuals/e274.webp', width: 627, height: 282 },
  290: { src: '/journal/elite-visuals/e290.webp', width: 807, height: 422 },
  299: { src: '/journal/elite-visuals/e299.webp', width: 775, height: 291 },
  302: { src: '/journal/elite-visuals/e302.webp', width: 964, height: 331 },
  312: { src: '/journal/elite-visuals/e312.webp', width: 828, height: 857 },
  318: { src: '/journal/elite-visuals/e318.webp', width: 584, height: 420 },
  324: { src: '/journal/elite-visuals/e324.webp', width: 610, height: 726 },
  330: { src: '/journal/elite-visuals/e330.webp', width: 478, height: 438 },
}

export function eliteVisualForEntry(n: number): Visual | null {
  return eliteVisuals[n] ?? null
}
