// Titles for Elite journal pages the printed book leaves untitled.
//
// Most Elite pages are one question and the space to answer it, with no
// heading above. The question belongs in the exercise, so the page still needs
// a name at the top, and these are written from what each page asks.
//
// Generated with review. Safe to hand-edit.

export const eliteTitles: Record<number, string> = {
  2: 'Your Default Setting',
  10: 'As We Are',
  3: 'Strengths Overdone',
  4: 'Both Sides of your Style',
  5: 'The Angle you Miss',
  6: 'The Cost of Blindspots',
  8: 'Borrow Another View',
  9: 'Where Balance Pays',
  11: 'Assumptions you Carry',
  12: 'Know When to Switch',
  15: 'What the Shift Revealed',
  16: 'Outgrow your Old Playbook',
  17: 'Your Awareness So Far',
  18: 'The Self you Resist',
  20: 'The Power of Small Adjustments',
  22: 'Tendency Over Destiny',
  23: 'A Fresh Look',
  24: 'Flexing with Ease',
  25: 'Try on Four Styles',
  26: 'Worth an Experiment',
  27: 'How you Show Up Now',
  30: 'When you Feel Alive',
  31: 'The Quiet Guides',
  32: 'Looking Inward',
  33: 'Fully Yourself',
  34: 'The Price of Compromise',
  36: 'Where Words and Actions Part',
  37: 'Your Drift Triggers',
  38: 'Doing Over Saying',
  39: 'Decide by your Values',
  40: 'Values in the Everyday',
  41: 'Choose a Third Value',
  43: 'How your Values Fit',
  44: 'Become What you Do',
  45: 'The Easier Hard Choice',
  46: 'Where you Hold Back',
  48: 'A Clearer Direction',
  50: 'Passion is Not Random',
  51: 'Anchors for your Values',
  52: 'Values in Other People',
  54: 'What your Choices Build',
  55: 'Keeping Yourself Honest',
  58: 'Strengths on Purpose',
  59: 'Strengths Left Idle',
  60: 'What you Have',
  61: 'Too Much of a Strength',
  62: 'Design your Days',
  64: 'How your Strengths Interact',
  65: 'Room to Amplify',
  66: 'Not Good at Everything',
  67: 'Fixing or Maximising',
  68: 'Borrow Their Strengths',
  71: 'A Strength for Today',
  73: 'Strengths and your Energy',
  74: 'Leading with Strengths',
  76: 'Why Strengths Feel Uncomfortable',
  79: 'The Unfair Comparison',
  80: 'Own your Difference',
  82: 'Your Strengths Pattern',
  83: 'Keep Building',
  86: 'The Feelings you Avoid',
  87: 'The Cost of Avoiding',
  88: 'Still Water',
  89: 'React or Respond',
  90: 'Thoughts Are Not Facts',
  92: 'The Stories your Mind Tells',
  93: 'Not Every Thought is True',
  94: 'Where Focus Goes',
  95: 'Handle Thoughts Differently',
  96: 'Too Much Power',
  99: 'The Space Between',
  100: 'From Thought to Performance',
  101: 'Emotions as Information',
  102: 'Observe Without Obeying',
  104: 'What No Longer Serves',
  107: 'Discomfort Worth Having',
  108: 'You and your Thoughts',
  110: 'Stuck on Automatic',
  111: 'Practise Flexibility',
  114: 'Where Control Lives',
  115: 'Reclaim a Small Choice',
  116: 'Fleeting or Lasting',
  117: 'Progress you Overlooked',
  118: 'The Wrong Yardstick',
  120: 'Progress Over Perfection',
  121: 'The Comparison Trap',
  122: 'Motivation from Within',
  123: 'People Who Fuel you',
  124: 'Find your Crowd',
  127: 'Going it Alone',
  128: 'Hold the Strings',
  129: 'Stop Waiting for Motivation',
  130: 'Make Motivation Inevitable',
  132: 'Cut the Drains',
  134: 'Architect of your Environment',
  135: 'A Daily Anchor',
  136: 'Motion is Not Progress',
  138: 'Driven from Inside',
  139: 'When the Fire Dims',
  141: 'Name your Ideal Outcome',
  142: 'What Worry Hides',
  143: 'Optimism or Naivety',
  144: 'A Different Lens',
  145: 'Win or Not Lose',
  146: 'Your Challenge Narrative',
  148: 'Stuck on the Problem',
  149: 'Shift to Solutions',
  150: 'Hope with Clear Eyes',
  151: 'Waiting for Perfect',
  152: 'The Agency you Have',
  153: 'Build the Action Plan',
  155: 'Evidence Against the Story',
  156: 'Optimistic and Realistic',
  157: 'The Use of Pessimism',
  158: 'Prepared and Hopeful',
  159: 'Lessons from Past Wins',
  160: 'Proof you Can Cope',
  162: 'Keep Taking the Shot',
  163: 'Growing Realistic Hope',
  164: 'Lead with Possibility',
  166: 'Guard Against Cynicism',
  167: 'Stay Focused on Solutions',
  170: 'Safe to Be Open',
  171: 'What Stops you Asking',
  172: 'Inside the Bottle',
  173: 'An Outside View',
  174: 'A Network by Design',
  176: 'Hand it Over',
  177: 'The Help you Refused',
  178: 'The Old Map',
  179: 'Where Knowledge Comes from',
  180: 'The Expertise you Need',
  183: 'Those Who Taught you',
  184: 'Shoulders of Giants',
  185: 'Someone Who Believes',
  186: 'Surprising Feedback',
  188: 'Lift Someone Else',
  190: 'Widen your Horizon',
  191: 'Pick your Squad',
  192: 'Asking is Strength',
  194: 'Your Squad Now',
  195: 'Where to Invest',
  198: 'Your Ideal Conditions',
  199: 'Deep or Shallow',
  200: 'Forcing or Allowing',
  201: 'Losing Track of Time',
  202: 'Where Time Disappears',
  204: 'How you Break Focus',
  205: 'Guard the Deep Hours',
  206: 'Skill Meets Challenge',
  207: 'Signal the Start',
  208: 'Your Environment and Flow',
  211: 'Tune your Ritual',
  212: 'Between Boredom and Anxiety',
  213: 'The Tipping Point',
  214: 'Calibrate the Difficulty',
  216: 'The Right Level',
  218: 'Work or Play',
  219: 'Fully Present',
  220: 'Flow Every Day',
  222: 'Flow and your Work',
  223: 'Regular Access to Flow',
  226: 'Where you Resist',
  227: 'Practise in Small Ways',
  228: 'No Single Recipe',
  229: 'The Cost of Familiar',
  230: 'Change as Opportunity',
  232: 'Where you Go Rigid',
  233: 'Your Rules About Should',
  234: 'Unlearn to Learn',
  235: 'Proof you Can Adapt',
  236: 'What Steadies you',
  239: 'Move with the Change',
  240: 'What you Can Change',
  241: 'Consistent or Rigid',
  242: 'Strengths While Adapting',
  244: 'Adapt Without Compromising',
  246: 'Build the New',
  247: 'What to Let Go',
  248: 'Embracing the Unknown',
  250: 'Keep Adapting',
  251: 'Ready for This Change',
  254: 'Trust your First Reaction',
  255: 'Your Emotional Patterns',
  256: 'Full Mind or Mindful',
  257: 'Insights in Plain Sight',
  258: 'When you Pause',
  260: 'Bias in your Judgement',
  261: 'Through Someone Else\'s Eyes',
  262: 'Growth Follows Awareness',
  263: 'The Lesson you Resist',
  264: 'The Same Mistake Again',
  267: 'Rigour in Reflection',
  268: 'Reflection Before Action',
  269: 'The Feedback you Avoid',
  270: 'Ego in the Way',
  271: 'Go Beneath the Surface',
  272: 'Amplify What Works',
  274: 'Direction Over Speed',
  275: 'What Reflection Has Changed',
  276: 'Carry Reflection Forward',
  278: 'Reflection as Accelerator',
  279: 'Visible Only in Stillness',
  282: 'Direction Over Destination',
  283: 'Who you Must Become',
  285: 'Legacy in Daily Choices',
  286: 'Check your Trajectory',
  288: 'Pull or Push',
  289: 'If you Could Not Fail',
  290: 'Think Big, Move Small',
  291: 'Goals That Change you',
  292: 'The Fear of Success',
  295: 'Signs of Progress',
  296: 'Goals and Systems',
  297: 'Quitting Too Early',
  298: 'Make Progress Visible',
  299: 'Do the Verb',
  300: 'What Stands in the Way',
  302: 'Start Creating',
  303: 'How you Track',
  304: 'Obstacles you Can Expect',
  306: 'The Smallest Next Step',
  307: 'Flexible and Committed',
  310: 'Body and Mind',
  311: 'The Neglected Dimension',
  312: 'Wellbeing as Energy',
  313: 'Sleep and Performance',
  314: 'Movement That Restores',
  316: 'More of What Lifts you',
  317: 'Less of What Drains you',
  318: 'Master the Seasons',
  319: 'Signals for Recovery',
  320: 'Rest with Intent',
  323: 'Raise your Floor',
  324: 'That Little Extra',
  325: 'Excellence Over Years',
  326: 'Push and Recover',
  328: 'Your Biggest Change',
  330: 'The Happiness of Pursuit',
  331: 'Who you Have Become',
  332: 'Who Comes Next',
  334: 'What is Possible Now',
  335: 'Keep Evolving',
  78: 'The Unconscious Made Conscious',
}
