// Generated by scripts/crop-elite-visuals.py. Do not hand-edit.
//
// The artwork from each Elite entry page, cropped away from the ruled
// writing lines and the prompt boxes. Rendered on a flat ground with
// multiply blending, so the white of the page drops out.

import type { Visual } from './journal-visuals'

/** True where the crop contains printed words as well as the drawing. */
export type EliteVisual = Visual & { coversText: boolean }

const eliteVisuals: Record<number, EliteVisual> = {
  1: { src: '/journal/elite-visuals/e001.webp', width: 883, height: 879, coversText: false },
  10: { src: '/journal/elite-visuals/e010.webp', width: 686, height: 614, coversText: false },
  16: { src: '/journal/elite-visuals/e016.webp', width: 891, height: 481, coversText: true },
  22: { src: '/journal/elite-visuals/e022.webp', width: 651, height: 218, coversText: false },
  32: { src: '/journal/elite-visuals/e032.webp', width: 729, height: 767, coversText: true },
  38: { src: '/journal/elite-visuals/e038.webp', width: 709, height: 381, coversText: false },
  44: { src: '/journal/elite-visuals/e044.webp', width: 626, height: 344, coversText: false },
  50: { src: '/journal/elite-visuals/e050.webp', width: 548, height: 548, coversText: false },
  60: { src: '/journal/elite-visuals/e060.webp', width: 798, height: 473, coversText: false },
  66: { src: '/journal/elite-visuals/e066.webp', width: 793, height: 549, coversText: false },
  69: { src: '/journal/elite-visuals/e069.webp', width: 1063, height: 546, coversText: false },
  78: { src: '/journal/elite-visuals/e078.webp', width: 674, height: 826, coversText: false },
  85: { src: '/journal/elite-visuals/e085.webp', width: 712, height: 705, coversText: true },
  88: { src: '/journal/elite-visuals/e088.webp', width: 763, height: 519, coversText: true },
  94: { src: '/journal/elite-visuals/e094.webp', width: 428, height: 397, coversText: false },
  97: { src: '/journal/elite-visuals/e097.webp', width: 868, height: 798, coversText: true },
  100: { src: '/journal/elite-visuals/e100.webp', width: 574, height: 592, coversText: false },
  103: { src: '/journal/elite-visuals/e103.webp', width: 826, height: 798, coversText: true },
  116: { src: '/journal/elite-visuals/e116.webp', width: 757, height: 396, coversText: false },
  122: { src: '/journal/elite-visuals/e122.webp', width: 310, height: 608, coversText: false },
  128: { src: '/journal/elite-visuals/e128.webp', width: 693, height: 622, coversText: false },
  134: { src: '/journal/elite-visuals/e134.webp', width: 583, height: 1177, coversText: false },
  144: { src: '/journal/elite-visuals/e144.webp', width: 697, height: 519, coversText: false },
  150: { src: '/journal/elite-visuals/e150.webp', width: 533, height: 485, coversText: false },
  156: { src: '/journal/elite-visuals/e156.webp', width: 688, height: 573, coversText: false },
  162: { src: '/journal/elite-visuals/e162.webp', width: 806, height: 275, coversText: false },
  172: { src: '/journal/elite-visuals/e172.webp', width: 593, height: 546, coversText: false },
  178: { src: '/journal/elite-visuals/e178.webp', width: 461, height: 542, coversText: false },
  184: { src: '/journal/elite-visuals/e184.webp', width: 732, height: 453, coversText: false },
  190: { src: '/journal/elite-visuals/e190.webp', width: 589, height: 690, coversText: false },
  200: { src: '/journal/elite-visuals/e200.webp', width: 598, height: 360, coversText: false },
  206: { src: '/journal/elite-visuals/e206.webp', width: 644, height: 403, coversText: false },
  212: { src: '/journal/elite-visuals/e212.webp', width: 590, height: 612, coversText: false },
  218: { src: '/journal/elite-visuals/e218.webp', width: 594, height: 677, coversText: false },
  228: { src: '/journal/elite-visuals/e228.webp', width: 606, height: 605, coversText: false },
  234: { src: '/journal/elite-visuals/e234.webp', width: 630, height: 658, coversText: false },
  240: { src: '/journal/elite-visuals/e240.webp', width: 544, height: 582, coversText: false },
  246: { src: '/journal/elite-visuals/e246.webp', width: 610, height: 1028, coversText: false },
  253: { src: '/journal/elite-visuals/e253.webp', width: 835, height: 651, coversText: true },
  256: { src: '/journal/elite-visuals/e256.webp', width: 697, height: 297, coversText: false },
  259: { src: '/journal/elite-visuals/e259.webp', width: 835, height: 651, coversText: true },
  262: { src: '/journal/elite-visuals/e262.webp', width: 540, height: 747, coversText: false },
  265: { src: '/journal/elite-visuals/e265.webp', width: 835, height: 651, coversText: true },
  268: { src: '/journal/elite-visuals/e268.webp', width: 618, height: 651, coversText: false },
  274: { src: '/journal/elite-visuals/e274.webp', width: 627, height: 282, coversText: false },
  290: { src: '/journal/elite-visuals/e290.webp', width: 807, height: 422, coversText: false },
  299: { src: '/journal/elite-visuals/e299.webp', width: 775, height: 291, coversText: false },
  302: { src: '/journal/elite-visuals/e302.webp', width: 964, height: 331, coversText: false },
  312: { src: '/journal/elite-visuals/e312.webp', width: 828, height: 857, coversText: false },
  318: { src: '/journal/elite-visuals/e318.webp', width: 584, height: 420, coversText: false },
  324: { src: '/journal/elite-visuals/e324.webp', width: 610, height: 726, coversText: false },
  330: { src: '/journal/elite-visuals/e330.webp', width: 478, height: 438, coversText: false },
}

export function eliteVisualForEntry(n: number): EliteVisual | null {
  return eliteVisuals[n] ?? null
}
