// Generated from LP_Limitless_Journal_Combined_01.pdf. Do not hand-edit.
// Regenerate with scripts/parse-journal.py.

export type JournalEntry = {
  n: number
  week: number
  title: string | null
  prompts: string[]
  /** Some entries face a quotation page in the printed journal. */
  quote?: { text: string; author: string }
}

export const journalEntries: JournalEntry[] = [
  { n: 1, week: 1, title: 'Uncover your Behavioural Style', prompts: ['Scan the QR code, digest your results, and plot them below:', 'Describe an experience when your lead behavioural style served you well:', 'Describe an experience when your lead behavioural style might have been overdone:'] },
  { n: 2, week: 1, title: 'Finding your Balance', prompts: ['Reflect on a recent situation where your natural approach may have been too strong.', 'How could considering these different perspectives have led to a better outcome:', 'The goal is to expand your thinking while staying true to your authentic style. Use these', 'prompts as gentle reminders rather than strict rules.'] },
  { n: 3, week: 1, title: 'Change the Way you See Things', prompts: ['Identify an opportunity today to shift your behavioural style:'] },
  { n: 4, week: 1, title: 'Connect the Dots', prompts: ['What impact did your change in approach have yesterday?'] },
  { n: 5, week: 1, title: null, prompts: ['Ok, now what’s the plan of action:', 'What if you were more outspoken and confident?', 'What if you were to be more logical and factual?', 'What if you were more faithful and trusting?', 'What if you were more open and imaginative?'] },
  { n: 6, week: 1, title: null, prompts: [] },
  { n: 7, week: 1, title: 'Huddle', prompts: ['How can you apply shifting your natural approach on a more regular basis?'] },
  { n: 8, week: 2, title: 'Decode your Values', prompts: ['Identify the values that are important to you and fill you with a feeling of purpose.', 'Consider the following questions and select as many as you like:', 'Does this define me? Is this who I am at my best? Is this a filter that I use to make hard decisions?', 'From those selected, condense your values down to the two that resonate most with you:'] },
  { n: 9, week: 2, title: 'Living with Intent', prompts: ['With your two core values in mind (Entry 8), reflect on the following:', 'What behaviours are currently supporting your values?', 'Describe a time when you were fully living into your values?', 'Identify three slippery behaviours that cause you to act outside your values:'] },
  { n: 10, week: 2, title: null, prompts: ['Revisit your list of values from Entry 8 and select a third value that resonates with you:', 'Describe how this value might show up in your future actions?', 'Over the coming days, set a goal that aligns with your newly chosen value:', 'What does that experience look like? And how might it play out?'] },
  { n: 11, week: 2, title: null, prompts: [] },
  { n: 12, week: 2, title: 'Values in Motion', prompts: ['What guardrails might prevent you from living outside of your three values?', 'Reflect on how embodying your values has influenced your sense of purpose this week:', 'What were your biggest wins related to living your values?', 'When did you feel most energised and aligned with your values?', 'Were there moments you struggled to stay true to your values?'] },
  { n: 13, week: 2, title: null, prompts: [] },
  { n: 14, week: 2, title: 'Huddle', prompts: ['How will you continue to act in alignment with your three values moving forward?'] },
  { n: 15, week: 3, title: 'Your Zone of Genius', prompts: ['Think of a specific time when you were at your very best. Develop a detailed story around that', 'experience, focusing on the qualities that made you feel authentic and energised.', 'Write your story as concretely as you can. Allow the facts of the story to demonstrate your', 'strengths. What happened in the situation? What role did you play? What did you do that was', 'particularly successful or useful to someone? What did you feel and experience?'] },
  { n: 16, week: 3, title: 'Lean in', prompts: ['Go back and read your story from Entry 15. Write down any words or phrases you consider to be', 'related to your personal strengths:'] },
  { n: 17, week: 3, title: 'Amplify your Impact', prompts: ['What strength sets you apart from others? The thing you’re really good at:', 'How does it look in it’s sweetspot?', 'What does it look like when overdone?', 'What does it look like when underdone?'] },
  { n: 18, week: 3, title: null, prompts: [] },
  { n: 19, week: 3, title: 'The Dose Makes the Poison', prompts: ['What reminders can you give yourself to keep your strengths in balance?', 'What can you share with others to get the best out of you?'] },
  { n: 20, week: 3, title: null, prompts: [] },
  { n: 21, week: 3, title: 'Huddle', prompts: ['What actions will you take to develop it?', 'From those answers, identify your super strength. Your super strength is:', 'Now, ask someone who knows you well: What do they think you’re exceptionally good at that', 'gives you a competitive edge?', 'What are you best at that gives you a unique competitive edge?'] },
  { n: 22, week: 4, title: 'Reveal your Blindspots', prompts: ['How has your response to situations changed with this self-awareness?', 'How has understanding your personality traits influenced your decisions, interactions, and', 'personal growth?'] },
  { n: 23, week: 4, title: null, prompts: [] },
  { n: 24, week: 4, title: 'Decode your Actions', prompts: ['Reflect on how you can continue to ensure they guide your future choices:', 'Revisit the values you identified in Entry 8. How have these core values shaped your actions', 'and decisions recently?'] },
  { n: 25, week: 4, title: null, prompts: [] },
  { n: 26, week: 4, title: 'Strengths Multiplier', prompts: ['Reflect on how to keep your super strength in balance without over-doing or under-doing it:', 'Think about your personal strengths that you explored in Entry 17. How have you used these', 'strengths in the last three weeks?'] },
  { n: 27, week: 4, title: null, prompts: [] },
  { n: 28, week: 4, title: 'Huddle', prompts: ['Reflect on the most significant change in yourself over the past four weeks.', 'What actions or thoughts led to this shift?'] },
  { n: 29, week: 5, title: 'The Agile Mind', prompts: ['1. How open and accepting are you towards your thoughts and emotions?', '2. How much do you try to push away difficult thoughts or avoid unwanted emotions?', '3. How much do you engage in behaviours aligned with your values and goals?', 'How to ‘win’ at self-talk:'] },
  { n: 30, week: 5, title: null, prompts: ['When we’re in challenging situations, experiencing difficult thoughts and feelings, we face a crucial', 'choice. We can either unhook from our thoughts and respond proactively, or stay hooked and', 'react negatively.'] },
  { n: 31, week: 5, title: null, prompts: [] },
  { n: 32, week: 5, title: null, prompts: ['Identify a current challenging situation. Reflect on:', 'Acting ineffectively', 'and unlike the sort of', 'person you want to be.'] },
  { n: 33, week: 5, title: null, prompts: ['Identify a current challenging situation. Reflect on:', 'Acting effectively and', 'like the sort of person', 'you want to be.'] },
  { n: 34, week: 5, title: null, prompts: [] },
  { n: 35, week: 5, title: 'Huddle', prompts: ['What am I resisting right now, and how can I make space for it?', 'What is hapenning right here, right now, that I can notice fully?', 'What small step can I take today that aligns with my values?'] },
  { n: 36, week: 6, title: 'Motivation Check-in', prompts: ['Scan the QR Code and add your results below:', 'Does this reflect how you feel on a daily basis?', 'What’s one small way you could boost your lowest-scoring need this week?'] },
  { n: 37, week: 6, title: 'Bring the Ball Into your Court', prompts: ['Identify an area of your life where you feel you have limited autonomy. What changes could you', 'make to increase your sense of personal control?'] },
  { n: 38, week: 6, title: null, prompts: [] },
  { n: 39, week: 6, title: 'Feel and See your Progress', prompts: ['Pick a skill or task you want to work on. Identify ways you can make progress on it today:'] },
  { n: 40, week: 6, title: null, prompts: [] },
  { n: 41, week: 6, title: 'Power in Connection', prompts: ['Reach out to someone today. A quick chat, a thoughtful message, or a catchup. Reflect on:', 'No forced cheer, just honest reflection on human connection. Add any notes below:'] },
  { n: 42, week: 6, title: 'Huddle', prompts: ['What motivated you this week? And why?'] },
  { n: 43, week: 7, title: 'Stairway to Optimism', prompts: ['Identify an ideal outcome you’re working towards:', 'What’s the best case scenario?', 'What are the potential obstacles?', 'Based on this, score the likelihood of your ideal outcome happening:'] },
  { n: 44, week: 7, title: null, prompts: [] },
  { n: 45, week: 7, title: 'Stairway to Optimism', prompts: ['With the challenge from Entry 43 in mind, list your available resources:', 'Based on this, score the likelihood of your ideal outcome happening:'] },
  { n: 46, week: 7, title: null, prompts: [] },
  { n: 47, week: 7, title: null, prompts: ['For each step, write down how you’ll take full responsibility:', 'Craft a positive, realistic narrative about your approach:', 'Create a detailed action plan for your challenge:', 'Based on this, score the likelihood of your ideal outcome happening:'] },
  { n: 48, week: 7, title: null, prompts: [] },
  { n: 49, week: 7, title: 'Huddle', prompts: ['What strengths will you draw on?', 'Recall a past success, what lessons can you apply to your challenge:', 'Based on this, score the likelihood of your ideal outcome happening:'] },
  { n: 50, week: 8, title: 'C.h.o.i.c.e', prompts: ['C - Contact the present moment:', 'Apply the CHOICE framework to a recent or upcoming challenge:', 'H - Hold unwanted experiences lightly:', 'O - Observe internal experiences as they pass:', 'I - Identify what matters most:', 'C - Clarify goals and actions:', 'E - Engage in value-driven, committed action:'] },
  { n: 51, week: 8, title: null, prompts: [] },
  { n: 52, week: 8, title: 'Motivation Check-in', prompts: ['Revisit the QR Code and add your results below:', 'Have you noticed any changes in your motivation drivers? (Refer back to Entry 36)', 'One key takeaway to remember going forward?'] },
  { n: 53, week: 8, title: null, prompts: [] },
  { n: 54, week: 8, title: 'Realistic Optimists', prompts: ['Which traits are your strengths? Which need work?', 'Review the 10 traits of Realistic Optimists. For each, rate yourself 1-10:', 'SELECTIVE FOCUS (Disciplined, Purposeful, Intentional)', 'SET REALISTIC GOALS (Measurable, Attainable, Structured)', 'KEEP PERSPECTIVE (Objective, Level-headed, Contextual)', 'EMPHASISE POSITIVES (Strengths-based, Encouraging, Solution-oriented)', 'USE HUMOUR (Playful, Approachable, Relatable)', 'RATIONALITY (Logical, Reasoned, Evidence-based)', 'SELF-IMPROVEMENT (Ambitious, Reflective, Proactive)', 'EXPERIMENTATION (Innovative, Curious, Open-minded)', 'PERSONAL RESPONSIBILITY (Dependable, Self-reliant, Integrity-focused)', 'SELECT THEIR ENVIRONMENT (Intentional, Selective, Thoughtful)'] },
  { n: 55, week: 8, title: null, prompts: [] },
  { n: 56, week: 8, title: 'Huddle', prompts: ['Reflect on the most significant change you’ve noticed in yourself over the past four weeks.', 'What actions or thoughts led to this shift?'] },
  { n: 57, week: 9, title: 'Emotional Support Check-in', prompts: ['Today, have an open, vulnerable conversation with someone you trust. Share something that’s', 'been on your mind recently.', 'How did it feel to open up?', 'What response did you receive, and how did it impact you?', 'What new insights or perspectives did you gain from the conversation?'] },
  { n: 58, week: 9, title: 'Tangible Support Check-in', prompts: ['Think of a recent task that has been difficult to complete. Consider who or what could provide', 'resources or support to assist you.', 'What led you to select this resource or person?', 'What was your experience like when seeking and receiving assistance?', 'How did having this support influence your progress on the task?'] },
  { n: 59, week: 9, title: null, prompts: [] },
  { n: 60, week: 9, title: 'Informational Support Check-in', prompts: ['Find an expert or experienced individual to advise you on a current challenge.', 'What was the most valuable takeaway from their input?', 'How did their perspective shift your understanding of the situation?', 'How can you incorporate this type of support more frequently in the future?'] },
  { n: 61, week: 9, title: 'Esteem Support Check-in', prompts: ['Ask a trusted friend or mentor for honest, constructive feedback on a current goal or project.', 'What surprised you about their feedback?', 'How did this input affect your self-awareness?', 'How can you leverage their feedback to strengthen your esteem?'] },
  { n: 62, week: 9, title: null, prompts: [] },
  { n: 63, week: 9, title: 'Huddle', prompts: ['Identify four people who could form your core support network. For each person, note:', 'What unique expertise do they bring, how do they complement your strengths and limitations,', 'and how can you nurture these relationships?'] },
  { n: 64, week: 10, title: 'Flow Blockers', prompts: ['Over the day, log every distraction that pulls you off task. Be specific:', 'What patterns do you notice?', 'What’s your biggest flow killer/s?', 'Which distractions are external vs. internal?'] },
  { n: 65, week: 10, title: 'Flow Activation', prompts: ['Today, design a pre-flow ritual that signals your brain it’s time to dive deep. It could be a specific', 'playlist, a brief meditation, or arranging your workspace.', 'What steps make up your pre-flow ritual?', 'Having established your flow killers (Entry 64), what methods will you take to cut them out?'] },
  { n: 66, week: 10, title: null, prompts: [] },
  { n: 67, week: 10, title: 'Flow Triggers', prompts: ['Today, set up your schedule and work environment to make it as flow-conducive as possible:', 'Choose clear goals - does the task have a specific, finite outcome?', 'Make it easy to focus - where can you schedule your most productive time?', 'Make it challenging - how might you be able to make tasks the right amount of difficult?'] },
  { n: 68, week: 10, title: null, prompts: [] },
  { n: 69, week: 10, title: 'Flow Cycle', prompts: ['What activities can help you unwind and recharge? How does this ritual differ from your usual', 'break time?', 'Today, set up your post-flow recovery ritual:', 'How does it affect your energy levels, mood, and ability to re-engage with work? Are there any', 'unexpected benefits or challenges you’ve noticed?', 'Consider how your recovery ritual prepares you for future flow states. Identify the elements that', 'seem most effective in setting the stage for your next deep work session:'] },
  { n: 70, week: 10, title: 'Huddle', prompts: ['What moments this week did you feel most in the zone? What led to this?'] },
  { n: 71, week: 11, title: 'Adaptability Check-in', prompts: ['What’s a challenge you’ve faced:', 'Think of someone with a different natural behaviour style than yours. How would they have', 'approached the challenge differently?'] },
  { n: 72, week: 11, title: null, prompts: [] },
  { n: 73, week: 11, title: 'You Vs. Them', prompts: ['Refer back to your challenge in Entry 71, analyse the contrast in:', 'Based on that information, what conclusions can you make?', 'What future reminder can you give yourself to remain adaptable?'] },
  { n: 74, week: 11, title: null, prompts: [] },
  { n: 75, week: 11, title: 'Strategy Test', prompts: ['Today, define an objective clearly:', 'Brainstorm three unconventional approaches:', 'Challenge your instinctual approach:', 'Choose and implement the most adaptable approach:'] },
  { n: 76, week: 11, title: null, prompts: [] },
  { n: 77, week: 11, title: 'Huddle', prompts: ['If you want to change your approach to something, consider:', 'How can I make it easy and obvious?', 'How can I make it satisfying and rewarding?'] },
  { n: 78, week: 12, title: 'Support System Audit', prompts: ['Reflect on how you’ve used support from others over the past few weeks:', 'What was the most valuable takeaway from their input?', 'How did their perspective shift your understanding of the situation?', 'How can you incorporate this type of support more frequently in the future?'] },
  { n: 79, week: 12, title: null, prompts: [] },
  { n: 80, week: 12, title: 'Flow State Autopsy', prompts: ['Think of an experience where you felt completely in flow (engaged, focused) and one where you', 'felt out of flow (disengaged, distracted). Plot your skill and challenge level below:', 'In each experience, draw a line between skill and challenge. What do you notice?', 'What insights can you take moving forward?'] },
  { n: 81, week: 12, title: null, prompts: [] },
  { n: 82, week: 12, title: 'Adaptability in Action', prompts: ['Choose a recent situation where you were inflexible. Reimagine it:', 'What if you had to solve it using only what’s in this room?', 'What if you had to delegate the entire task?', 'What if you had to make it fun?', 'What if you had zero constraints?'] },
  { n: 83, week: 12, title: null, prompts: [] },
  { n: 84, week: 12, title: 'Huddle', prompts: ['Reflect on the most significant change you’ve noticed in yourself over the past four weeks.', 'What actions or thoughts led to this shift?'] },
  { n: 85, week: 13, title: 'Capturing the Moment', prompts: ['Consider an event or situation and answer the following questions (modified from Gibbs, 1988):', 'Feelings: What were you thinking and feeling?', 'Description: Describe what happened:'] },
  { n: 86, week: 13, title: null, prompts: [] },
  { n: 87, week: 13, title: 'Deeper Understanding', prompts: ['Consider an event or situation and answer the following questions (modified from Gibbs, 1988):', 'Analysis: Following further reflection and analysis, what else can you make of the situation?', 'Evaluation: What was good and bad about the experience?'] },
  { n: 88, week: 13, title: null, prompts: [] },
  { n: 89, week: 13, title: 'Shaping Tomorrow', prompts: ['Consider an event or situation and answer the following questions (modified from Gibbs, 1988):', 'Action plan: If the same situation occurred again, what would you do?', 'Conclusion: What else could you have done?'] },
  { n: 90, week: 13, title: null, prompts: [] },
  { n: 91, week: 13, title: 'Huddle', prompts: ['Self-reflection takes you down to your subconscious mind.', 'As a result of that process, you’re learning new things about yourself and are creating an ideal', 'decision-making tool for any intended behavioural change.', 'Take your time to gather insights, examine patterns that govern your actions, or the way you feel', 'and the way you think about things:'] },
  { n: 92, week: 14, title: 'Direction of Travel', prompts: ['What mission would you dedicate your life to? What problem would you solve? What legacy would', 'you build?', 'Don’t focus on specific goals. Think bigger. What’s the overarching purpose that would drive you', 'forward, even if you knew you’d never fully “arrive”?', 'Describe this infinite game you’d play, the journey you’d never tire of, the mission that would keep', 'you pushing boundaries year-after-year.', 'Remember: This isn’t about what’s “realistic.” It’s about uncovering the core drive that could fuel a', 'lifetime of growth and impact.'] },
  { n: 93, week: 14, title: 'Destination', prompts: ['Fast-forward 1-3 years from now. Visualise a specific, tangible achievement.', 'What have you accomplished?', 'Now, make it measurable. How will you know when you’ve arrived at this destination? What', 'specific metrics or outcomes define this success?', 'Remember: This isn’t your final stop, but a compelling destination on your longer journey. It should', 'stretch you, yet still feel achievable with focused effort.'] },
  { n: 94, week: 14, title: 'Milestones', prompts: ['Imagine your journey to your destination. You’re standing at the base of a mountain, looking up at', 'your summit.', 'Now, spot two ledges on your climb:', '1. The first ledge: What’s a milestone that’s challenging but achievable in the shorter term?', 'This is your first real taste of progress.', '2. The second ledge: What’s a significant milestone that puts you more than halfway to your', 'ultimate goal? This is where you can catch your breath and see how far you’ve come.', 'Remember: These are more than checkpoints. They’re opportunities to reflect, adjust, and', 'celebrate progress. Each one should energise you for the next climb.'] },
  { n: 95, week: 14, title: 'Systems', prompts: ['Envision your ideal day of progress. Now, zoom in on the essential actions:', 'Morning Ritual: Define the first hour that sets you up for success. Identify the habits that prime', 'your mind and body for peak performance.', 'Daily Keystone: Pinpoint the one action that, if done consistently, makes everything else easier or', 'unnecessary. This is your lever for exponential progress.', 'Energy Management: Map out your recharge points. Establish practices that maintain your peak', 'state throughout the day, preventing burnout and sustaining momentum.', 'Evening Wrap-up: Craft a closing routine that ensures tomorrow starts strong. Focus on reflection,', 'preparation, and mental reset.', 'For each action, think about its timing, triggers, and how to make it effortless to follow through.', 'Remember: These aren’t aspirational “shoulds.” They’re the concrete, non-negotiable actions', 'forming the backbone of your progress.'] },
  { n: 96, week: 14, title: null, prompts: [] },
  { n: 97, week: 14, title: null, prompts: [] },
  { n: 98, week: 14, title: 'Huddle', prompts: [] },
  { n: 99, week: 15, title: 'Periodise your Seasons', prompts: ['Anticipate the ebbs and flows of work and wellbeing over the coming year. Identify when to push', 'forward and when to recharge by shading in the boxes:'] },
  { n: 100, week: 15, title: 'Monthly Rhythms', prompts: ['Build restoration into your monthly planning before you need it. Strategic recovery prevents', 'fatigue and amplifies your next sprint.'] },
  { n: 101, week: 15, title: null, prompts: [] },
  { n: 102, week: 15, title: 'Daily Boundaries', prompts: ['Create intentional transition rituals and outline clear boundaries to fully separate work', 'intensity from personal restoration while maintaining excellence in both.'] },
  { n: 103, week: 15, title: null, prompts: [] },
  { n: 104, week: 15, title: 'Seasonal Flexibility', prompts: ['Different phases require different approaches - expand your range to thrive in any context.', 'When might you need to be more forceful and results-oriented?', 'When might you need to be more analytical and systematic?', 'When might you need to expand connections and seek input?', 'When might you need to focus on helping others and reflection?'] },
  { n: 105, week: 15, title: 'Huddle', prompts: [] },
  { n: 106, week: 16, title: 'Recalibrating', prompts: ['Have you used self-reflection to take more effective action? How might you use it more?'] },
  { n: 107, week: 16, title: null, prompts: [] },
  { n: 108, week: 16, title: 'Staying on Track', prompts: ['In order to meet your destination, when do you need to hit your milestones?', 'Are your daily systems helping you get there? If not, how can you make them? If yes, how can you', 'ensure you stick to them?'] },
  { n: 109, week: 16, title: null, prompts: [] },
  { n: 110, week: 16, title: 'Embrace the Seasons', prompts: ['Life moves in cycles — times to push, times to rest. Knowing where you are helps you work with', 'your rhythm, not against it.', 'What season are you in right now? How can you fully embrace it and reap its rewards?'] },
  { n: 111, week: 16, title: null, prompts: [] },
  { n: 112, week: 16, title: 'Huddle', prompts: ['Reflect on the most significant change you’ve noticed in yourself over the past four weeks.', 'What actions or thoughts led to this shift?'] },
]

export function entriesForWeek(week: number): JournalEntry[] {
  return journalEntries.filter((e) => e.week === week)
}

/** The first quotation printed in a given week, if there is one. */
export function quoteForWeek(week: number) {
  return entriesForWeek(week).find((e) => e.quote)?.quote
}
