/**
 * Seeds src/content/digests.ts from the Kit broadcast export.
 *
 *   npm run import:digests -- ../limitless-digests-export.md
 *
 * The export is one section per week, headed with the week number, the subject
 * line and the Kit broadcast id. This script splits it into the sections the
 * week pages render, and applies the house style: em dashes become commas or
 * full stops, and semicolons become full stops.
 *
 * It is deliberately conservative. Anything it cannot confidently classify is
 * left in `opening` and flagged on stdout for a human to place.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const source = process.argv[2]
if (!source) {
  console.error('Usage: npm run import:digests -- path/to/limitless-digests-export.md')
  process.exit(1)
}

const HEADINGS: Record<string, string> = {
  "this week's focus": 'focus',
  'this weeks focus': 'focus',
  'key insights': 'keyInsights',
  'key concepts': 'keyInsights',
  'implementation guide': 'implementation',
  'daily journal practice': 'dailyPractice',
  'weekly challenge': 'weeklyChallenge',
  'reflection questions': 'reflectionQuestions',
  'progress check': 'progressCheck',
  'connecting the dots': 'progressCheck',
  'looking ahead': 'lookingAhead',
  remember: 'remember',
}

/** House style. See section 8 of the brief. */
function style(text: string): string {
  return text
    .replace(/\s*—\s*/g, ', ')
    .replace(/\s*–\s*/g, ', ')
    .replace(/;\s*/g, '. ')
    .replace(/,\s*,/g, ',')
    .replace(/\s+/g, ' ')
    .trim()
}

const raw = readFileSync(source, 'utf8')
const blocks = raw.split(/^#\s+(?=Week\s+\d+)/im).filter(Boolean)

const digests = blocks.map((block) => {
  const week = Number(block.match(/Week\s+(\d+)/i)?.[1])
  const subject = style(block.match(/subject:\s*(.+)/i)?.[1] ?? '')
  const lines = block.split('\n')

  const out: Record<string, unknown> = { week, subject, opening: [], focus: [], keyInsights: [] }
  let current = 'opening'
  const unknown: string[] = []

  for (const line of lines) {
    const heading = line.match(/^#{2,4}\s*(.+?)\s*$/)
    if (heading) {
      const key = HEADINGS[heading[1].toLowerCase().replace(/[^a-z' ]/g, '').trim()]
      if (key) {
        current = key
        continue
      }
      if (/^the science behind/i.test(heading[1])) {
        current = 'science'
        continue
      }
      unknown.push(heading[1])
    }
    const text = style(line.replace(/^[-*]\s*/, ''))
    if (!text || /^week\s+\d+/i.test(text) || /^subject:/i.test(text)) continue
    const bucket = (out[current] ??= []) as string[]
    if (Array.isArray(bucket)) bucket.push(text)
  }

  if (unknown.length) {
    console.warn(`Week ${week}: unrecognised headings, left in opening: ${unknown.join(', ')}`)
  }
  return out
})

const body = `// Generated by scripts/import-digests.ts from the Kit export.
// Review before shipping: the importer flags anything it could not classify.

import type { Digest } from '../src/content/digests'

export const importedDigests: Digest[] = ${JSON.stringify(digests, null, 2)} as unknown as Digest[]
`

writeFileSync('src/content/digests.generated.ts', body)
console.log(`Wrote ${digests.length} digests to src/content/digests.generated.ts`)
