"""
Extracts the Elite journal into src/content/elite-journal.ts.

    pip install pymupdf
    python scripts/parse-elite-journal.py "vol1.pdf" "vol2.pdf" "vol3.pdf" "vol4.pdf"

The Elite journal is the same book design as the sixteen week one over three
hundred and thirty six pages instead of a hundred and twelve, bound as four
volumes of eighty four. Every page is the right hand side of a spread, with the
preview and review form facing it, so the reading of a page is identical and
this shares parse-journal's parser rather than restating it.

What is different is the arithmetic on top. Seven entries a week as before, but
twenty eight to a chapter and twelve chapters to the year, so an entry carries a
chapter as well as a week.

Volumes are passed in order and their entry numbers are trusted rather than
inferred from position, because the four files have been exported separately and
at different times. The script refuses to write anything unless all three
hundred and thirty six arrive exactly once: a stale volume that repeats or skips
a range is the one failure that would be invisible in the output.
"""
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("parse_journal", os.path.join(HERE, "parse-journal.py"))
pj = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pj)

import re

import pymupdf

TOTAL = 336
ENTRIES_PER_WEEK = 7
ENTRIES_PER_CHAPTER = 28


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit("give the journal volumes in order, volume 1 first")

    pj.TOTAL = TOTAL
    marker = re.compile(r"ENTRY\s*(\d+)\s*/\s*%d" % TOTAL)

    found = {}
    for volume, path in enumerate(sys.argv[1:], 1):
        doc = pymupdf.open(path)
        for page in doc:
            em = marker.search(page.get_text())
            if not em:
                continue
            n = int(em.group(1))
            if n in found:
                sys.exit(f"entry {n} appears twice: volume {found[n]['volume']} and volume {volume}")
            entry = pj.parse_entry(page)
            entry["n"] = n
            entry["week"] = (n - 1) // ENTRIES_PER_WEEK + 1
            entry["chapter"] = (n - 1) // ENTRIES_PER_CHAPTER + 1
            entry["volume"] = volume
            found[n] = entry
        print(f"volume {volume}: {sum(1 for e in found.values() if e['volume'] == volume)} entries")

    missing = [n for n in range(1, TOTAL + 1) if n not in found]
    if missing:
        sys.exit(f"missing {len(missing)} entries: {missing[:20]}")

    entries = [found[n] for n in range(1, TOTAL + 1)]

    out = [
        "// Generated by scripts/parse-elite-journal.py from the four printed volumes.",
        "// Do not hand-edit: rerun the parser instead.",
        "",
        "export type EliteJournalEntry = {",
        "  n: number",
        "  /** One of the forty eight weeks of the year. */",
        "  week: number",
        "  /** One of the twelve chapters. */",
        "  chapter: number",
        "  /** Which of the four printed books carries it. */",
        "  volume: number",
        "  title: string | null",
        "  /** Framing text that sets the exercise up. */",
        "  intro: string[]",
        "  /** The prompts to write against, in the order the book sets them. */",
        "  prompts: string[]",
        "  /** A closing note under the exercise. */",
        "  outro: string[]",
        "  /** The printed page carries a QR code here, replaced by a link. */",
        "  qr: boolean",
        "}",
        "",
        "export const eliteJournalEntries: EliteJournalEntry[] = [",
    ]
    for e in entries:
        out.append(
            "  { n: %d, week: %d, chapter: %d, volume: %d, title: %s, intro: %s, prompts: %s, outro: %s, qr: %s },"
            % (
                e["n"],
                e["week"],
                e["chapter"],
                e["volume"],
                pj.ts(e["title"]) if e["title"] else "null",
                pj.ts_list(e["intro"]),
                pj.ts_list(e["prompts"]),
                pj.ts_list(e["outro"]),
                "true" if e["qr"] else "false",
            )
        )
    out += [
        "]",
        "",
        "export function eliteJournalEntry(n: number): EliteJournalEntry | undefined {",
        "  return eliteJournalEntries.find((e) => e.n === n)",
        "}",
        "",
        "/** The seven entries of one of the forty eight weeks. */",
        "export function eliteEntriesForWeek(week: number): EliteJournalEntry[] {",
        "  return eliteJournalEntries.filter((e) => e.week === week)",
        "}",
        "",
        "/** The twenty eight entries of one chapter. */",
        "export function eliteEntriesForChapter(chapter: number): EliteJournalEntry[] {",
        "  return eliteJournalEntries.filter((e) => e.chapter === chapter)",
        "}",
        "",
    ]

    target = os.path.join(HERE, "..", "src", "content", "elite-journal.ts")
    with open(target, "w") as fh:
        fh.write("\n".join(out))

    titled = sum(1 for e in entries if e["title"])
    prompts = sum(len(e["prompts"]) for e in entries)
    print(f"{len(entries)} entries, {titled} titled, {prompts} prompts -> src/content/elite-journal.ts")


if __name__ == "__main__":
    main()
